name: Snyk Configuration and Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Snyk CLI
        run: |
          npm install -g snyk
        continue-on-error: false

      - name: Configure Snyk Endpoint
        run: |
          snyk config set endpoint=https://app.au.snyk.io/api
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: false

      - name: Configure Snyk Organization
        run: |
          snyk config set org=$SNYK_ORG
          snyk config get org
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_ORG: ${{ secrets.SNYK_ORG }}
        continue-on-error: false

      - name: Check Snyk Organization Environment Variable
        run: echo "Snyk Org ID is $SNYK_ORG"
        env:
          SNYK_ORG: ${{ secrets.SNYK_ORG }}

      - name: Run Snyk to check for vulnerabilities
        run: |
          snyk test || true  # Ensures the workflow continues even if vulnerabilities are found
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_ORG: ${{ secrets.SNYK_ORG }}
